import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const global_state = {
  player_0: {
    x: 0,
    y: 0,
  },
  player_1: {
    x: 0,
    y: 0,
  }
}

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export function Providers({ children } : { children: React.ReactNode }) {
  return (
    <>
      {children}
    </>
  );
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html className="w-screen h-screen overflow-hidden" lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}



